E-COMMERCE/E_COMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    # FOR MEDIA/FILE UPLOAD AND STORAGE
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),


    path('', views.home, name="HOME"),
    path('product/', include('PRODUCT.urls')),
    path('user/', include('USER.urls')),
    path('admin/', admin.site.urls),
]

E-COMMERCE/PRODUCT/urls.py
from django.urls import path 
from . import views

app_name = 'PRODUCT'

urlpatterns = [
    path('System_Builder/', views.system_builder, name="BUILD"),
    path('laptop/', views.laptop, name="LAPTOP"),
    path('pre_build/', views.pre_build_pc, name="PRE-BUILD")
]

E-COMMERCE/USER/urls.py
from django.urls import path
from . import views

app_name = 'USER'

urlpatterns = [
    path('login', views.login_user, name="LOGIN"),
    path('register/', views.register_user, name="REGISTER"),
    path('logout/', views.logout_user, name="LOGOUT"),
    path('cart/<str:userID>', views.getUserCart, name="FETCHCART"),
    path('cart/add/<str:product_type>/<str:userID>/<str:product_id>', views.addToCart, name="ADD_TO_CART")
]

E-COMMERCE/templates/home.html
{% extends "master.html" %}

{% block title %}
HOME | APPNAME
{% endblock  %}


{% block content %}

<section class="home-hero-section">
    <h1>TITLE HERE</h1>
    <h2>SUBTITLE HERE</h2>
    <p>Lorem ipsum, dolor sit amet consectetur 
        adipisicing elit. Nemo ratione necessitatibus 
        sint asperiores, totam non voluptatibus esse 
        accusantium ad, magni ullam accusamus soluta 
        fugit aut omnis, adipisci reicien</p>
    <button class="home-button-no1" onclick="location.href='/#home-latest-product-container'">button #1</button>
</section>

<!-- ===================================== LATEST PRODUCT DISPLAY ===================================== -->
<section id="home-latest-product-container">
    <div class="latest-product-container">
        <aside class="latest-product-text">
            <h1>LATEST BUILD</h1>
            <p>description description 
                description description
                description description
                description description
            </p>
            <button class="button2">Button #2</button>
        </aside>
        <ul class="list-ng-latest"> 
<!-- dito isangat ang DJANGO tags -->
<!-- product img,name,description,price and reviews dito -->
            {% for build in UserBuilds %}
            <li class="latest-product">
                <div class="latest-product-img">
                    <img src="" alt="image here">
                </div>
                <div class="latest-product-info">
                    <h1>{{build.bundle_name}}</h1>
                    <p>Lorem Ipsum...</p>
                </div>
                
                <div class="price-review">
                    <p>${{build.bundle_total_price}}</p>
                    <a href="">review</a>
                </div>
            </li>
            {% endfor %}
<!-- ==================================================== -->
            
            
        </ul>
    </div>
    
</section>
<!-- ===================================== PRE-BUILD SHOWCASE DISPLAY ===================================== -->

<section class="home-prebuilds">
    <div class="prebuild-product-container">
        <ul class="list-ng-prebuild">
            <div class="prebuild-product-container-text">
                <h1>Pre-Build Products</h1>
                <p>Lorem ipsum, dolor sit amet 
                    consectetur adipisicing elit. 
                    Eveniet mollitia voluptate magni s
                    uscipit dolore culpa, modi ipsa eaque.
                </p>
                <button class="button3">See More</button>
            </div>

            {% for build in PreBuilds %}
            <li class="prebuild-product">
                <div class="prebuild-product-img">
                    <img src="" alt="image here">
                </div>
                <div class="prebuild-product-info">
                    <h1>{{build.bundle_name}}</h1>
                    <p>Lorem Ipsum...</p>
                </div>
                
                <div class="prebuild-price-review">
                    <p>${{build.bundle_total_price}}</p>
                    <a href="">review</a>
                </div>
            </li>
            {% endfor %}
            
        </ul>
        
    </div>

</section>

{% endblock  %}

E-COMMERCE/templates/master.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            MASTER | APP
        {% endblock  %}
    </title>
    <link rel="stylesheet" href="{% static 'styles/master.css' %}">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <link rel="stylesheet" href="{% static 'styles/laptop.css' %}">
    <link rel="stylesheet" href="{% static 'styles/pre_build_pc.css' %}">
    <link rel="stylesheet" href="{% static 'styles/systemBuilder.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'styles/login.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'styles/register.css' %}">




</head>

    <style>
        *{
            margin:0;
        }
    </style>

<body>

    <nav class="Navigation">
        {% comment %} 
            THE STYLING GOES HERE
        {% endcomment %}
        <div class="logo-search-user-container">
          <h1 style="opacity: 0;">....</h1>
          <h1>PCNEED</h1>
          <div class="search-user-container">
              {% if request.user.is_authenticated %}
              
              <p>Hello {{request.user}}</p>
              <a href="{% url 'USER:LOGOUT' %}">Logout</a>
              <a href="{% url 'USER:FETCHCART' userID=request.user.id %}">Cart</a>

              {% else %}
              <a href="{% url 'USER:LOGIN' %}">Login</a>
              {% endif %}
          </div>
          
      </div>
        </div>
        <hr class="styled-hr">

        <ul>
          <li><a href="{% url 'HOME' %}">Home</a></li>
          <li><a href="{% url 'PRODUCT:BUILD' %}">System Builder</a></li>
          <li><a href="{% url 'PRODUCT:PRE-BUILD' %}">Prebuild PC</a></li>
          <li><a href="{% url 'PRODUCT:LAPTOP' %}">Laptop</a></li>
        </ul>

    </nav>




    
    <main>
        {% block content %}
            <p>MASTER INDEX</p>
        {% endblock  %}
    </main>


    <footer class="footer">
        <div class="footer-container">
          <div class="logo-section">
            <h2>YOUR LOGO</h2>
            <p>Your Tagline here</p>
          </div>
          <div class="links-section">
            <div class="link-column">
              <h3>Title here</h3>
              <ul>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
              </ul>
            </div>
            <div class="link-column">
              <h3>Title here</h3>
              <ul>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
              </ul>
            </div>
            <div class="link-column">
              <h3>Title here</h3>
              <ul>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
                <li>text</li>
              </ul>
            </div>
          </div>
          <div class="contact-section">
            <h3>Contact Us</h3>
            <div class="contact-icons">
              <div class="icon"></div>
              <div class="icon"></div>
              <div class="icon"></div>
              <div class="icon"></div>
            </div>
          </div>
        </div>
        <div class="footer-bottom">
          <p>©2024 COMPANY NAME, LLC. All rights reserved.</p>
        </div>
      </footer>

</body>
</html>