E-COMMERCE/E_COMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    # FOR MEDIA/FILE UPLOAD AND STORAGE
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),


    path('', views.home, name="HOME"),
    path('product/', include('PRODUCT.urls')),
    path('user/', include('USER.urls')),
    path('admin/', admin.site.urls),
]

E-COMMERCE/USER/urls.py
from django.urls import path
from . import views

app_name = 'USER'

urlpatterns = [
    path('login', views.login_user, name="LOGIN"),
    path('register/', views.register_user, name="REGISTER"),
    path('logout/', views.logout_user, name="LOGOUT"),
    path('cart/<str:userID>', views.getUserCart, name="FETCHCART"),
    path('cart/add/<str:product_type>/<str:userID>/<str:product_id>', views.addToCart, name="ADD_TO_CART")
]

E-COMMERCE/USER/models.py
from django.db import models
from django.contrib.auth.models import User
from PRODUCT.models import Laptop, PackageBundle



class Basket(models.Model):
    user_id = models.PositiveIntegerField()
    basket_item_id = models.PositiveIntegerField(default=0)
    basket_item_name = models.CharField(max_length=350)
    basket_item_price = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.basket_item_name

E-COMMERCE/USER/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from USER.models import Basket
from PRODUCT.models import Laptop, PackageBundle
from django.http import HttpResponse

# Create your views here.


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())

            # Creates a basket/cart upon a new user registration
            newBasket = Basket(user_id=request.user)
            newBasket.save()



            return redirect('PRODUCT:LAPTOP')
    else:
        form = UserCreationForm()

    return render(request, 'USER/registration.html',{
        'form': form
    })

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('PRODUCT:LAPTOP')
    else:
        form = AuthenticationForm()
    return render(request, 'USER/login.html',{
        'form':form
    })

def logout_user(request):
    logout(request)
    return redirect('HOME')

def getUserCart(request, userID):
    Items = Basket.objects.filter(user_id=userID)

    itemNames = []

    for item in Items:
        a.append(item.basket_item_name)

    return HttpResponse(f'{itemNames}')



def addToCart(request, product_type, userID, product_id):
    if product_type == 'DESKTOP':
        product = PackageBundle.objects.get(unit_id=product_id)
    elif product_id == 'LAPTOP':
        product = Laptop.objects.get(lap_id=product_id)
    
    insertBasket = Basket(
        user_id=userID,
        basket_item_id=product_id,
        basket_item_name=product.name,
        basket_item_price=product.price
    )

    return HttpResponse(f'{product} is ADDED')


E-COMMERCE/USER/templates/USER/login.html
{% extends "master.html" %}


{% block title %}
    Login | APP
{% endblock  %}

{% block content %}

<section class="login-form-container">
    <div class="login-form">
        <form method="post" action="" >
            {% csrf_token %}

            {{form}}

            <button type="submit" value="Login"  class="loginbtn">Login</button>
        </form>
    
        <p>haven't signed up yet ?</p>
        <a href="{% url 'USER:REGISTER' %}">Sign Up</a>
    </div>
</section>

{% endblock  %}

E-COMMERCE/USER/templates/USER/registration.html
{% extends "master.html" %}


{% block title %}
    Register | APP
{% endblock  %}

{% block content %}

<div id="container-register">
    <div id="title">
        <i class="material-icons lock">|</i> Register
    </div>

    <form method="post" action="">
        {% csrf_token %}
        {{form}}

        <input type="submit" value="Register" />
    </form>

    <div class="privacy">
        <a href="#">Privacy Policy</a>
    </div>

    <div class="register">
        Do you already have an account?
        <a href="{% url 'USER:LOGIN' %}"><button id="register-link">Log In here</button></a>
    </div>
</div>

{% endblock  %}