E-COMMERCE/E_COMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    # FOR MEDIA/FILE UPLOAD AND STORAGE
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),


    path('', views.home, name="HOME"),
    path('product/', include('PRODUCT.urls')),
    path('user/', include('USER.urls')),
    path('admin/', admin.site.urls),
]

E-COMMERCE/PRODUCT/urls.py
from django.urls import path 
from . import views

app_name = 'PRODUCT'

urlpatterns = [
    path('System_Builder/', views.system_builder, name="BUILD"),
    path('laptop/', views.laptop, name="LAPTOP"),
    path('pre_build/', views.pre_build_pc, name="PRE-BUILD")
]

E-COMMERCE/USER/urls.py
from django.urls import path
from . import views

app_name = 'USER'

urlpatterns = [
    path('login', views.login_user, name="LOGIN"),
    path('register/', views.register_user, name="REGISTER"),
    path('logout/', views.logout_user, name="LOGOUT"),
    path('cart/<str:userID>', views.getUserCart, name="FETCHCART"),
    path('cart/add/<str:product_type>/<str:userID>/<str:product_id>', views.addToCart, name="ADD_TO_CART")
]

E-COMMERCE/PRODUCT/models.py
from django.db import models

# imports model from different application
from STORE.models import Store


# Create your models here.

class Parts(models.Model):
    category = [
        ('Motherboard','Motherboard'),
        ('CPU','CPU'),
        ('Storage','Storage'),
        ('Memory','Memory'),
        ('Power Supply Unit', 'Power Supply Unit'),
        ('CPU Cooler', 'CPU Cooler'),
        ('Graphics Card','Graphics Card'),
        ('Case','Case')
    ]

    parts_id = models.BigAutoField(null=False, primary_key=True)
    parts_store = models.ForeignKey(Store, on_delete=models.CASCADE, default=None)
    parts_category = models.CharField(max_length=200, choices=category, default=category[0])
    parts_name = models.CharField(max_length=200)
    parts_description = models.TextField()
    parts_img = models.ImageField(default='Desert.jpg')
    parts_price = models.BigIntegerField()
    parts_quantity = models.BigIntegerField()
    parts_rate = models.BigIntegerField(default=0)
    isSoldOut = models.BooleanField(default=False)



    def __str__(self) -> str:
        return self.parts_name


class PackageBundle(models.Model):
    category = [
        ('PreBuild','PreBuild'),
        ('UserBuild','UserBuild')
    ]


    unit_id = models.BigAutoField(null=False, primary_key=True)
    bundle_category = models.CharField(max_length=100, choices=category, default=category[0])
    bundle_banner = models.ImageField(default='Desert.jpg')
    
    name = models.CharField(max_length=200)
    motherboard_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_motherboard')
    processor_unit= models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_processor')
    storage_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None,related_name='bundle_storage')
    memory_unit= models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_memory')

    # PERIPHERALS
    PSU_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_PSU')
    CPU_cooler_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_CPU_COOLER')
    GPU_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_GPU')
    case_unit = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None, related_name='bundle_case')

    price = models.BigIntegerField(default=0)

    def __str__(self) -> str:
        return self.name



class Laptop(models.Model):
    lap_id = models.AutoField(primary_key=True)
    banner = models.ImageField(default='Hydrangeas.jpg')


    name = models.CharField(max_length=100)

    processor = models.CharField(max_length=100)
    os = models.CharField(max_length=100)
    graphic_card = models.CharField(max_length=100)
    memory = models.CharField(max_length=100)
    storage = models.CharField(max_length=100)
    display = models.CharField(max_length=100)
    camera = models.CharField(max_length=100)
    battery = models.CharField(max_length=100)
    keyboard = models.CharField(max_length=100)
    wifi = models.CharField(max_length=100)
    warranty = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    price = models.BigIntegerField(default=150)

    def __str__(self):
        return self.name


class Review(models.Model):
    review_id = models.BigAutoField(null=False, primary_key=True)
    product_topic = models.ForeignKey(Parts, on_delete=models.CASCADE, default=None)
    # review_author
    review_context = models.TextField()


    def __str__(self) -> str:
        return self.review_context

E-COMMERCE/PRODUCT/views.py
from django.shortcuts import render
from PRODUCT.models import PackageBundle, Laptop


# Create your views here.


# SYSTEM BUILDER SECTION
def system_builder(request):
    return render(request, 'PRODUCT/system_builder.html')


# PRE-BUILD PC SECTION
def pre_build_pc(request):
    prebuild = PackageBundle.objects.filter(bundle_category='PreBuild')
    return render(request, 'PRODUCT/pre_build_pc.html',{'prebuilds':prebuild})


#LAPTOP SECTION
def laptop(request):
    laptops = Laptop.objects.all()
    return render(request, 'PRODUCT/laptop.html',{'laptops':laptops})

def check_out(request):
    return render(request, 'PRODUCT/check_out.html')

def add_cart(request):
    return render(request, 'PRODUCT/addtocart.html')

E-COMMERCE/PRODUCT/templates/PRODUCT/addtocard.html
<H1>ADD TO CART PAGE</H1>

E-COMMERCE/PRODUCT/templates/PRODUCT/check_out.html
<h1>CHECKOUT PAGE</h1>

E-COMMERCE/PRODUCT/templates/PRODUCT/laptop.html
{% extends 'master.html' %}

{% block title %}Laptop{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/styles/laptop.css' %}">

<div class="nav-title">
    <h1>Laptop</h1>
    <p>
        <!-- to HOME                             current page -->
        <a href="#">Home</a> > <a href="#">Laptop</a>
    </p>
</div>

<section class="content">
  <!-- Filter Bar -->
<div class="filter-bar">
  <h5>PRODUCTS</h5>
  <select>
  <option>Text here</option>
  <!-- Add more options if needed -->
  </select>
  <select>
      <option>Text here</option>
      <!-- Add more options if needed -->
  </select>
  <input type="text" placeholder="Search here...                                           🔍">
</div>

  <!-- Product Grid -->
<section class="product-grid">
  <!-- Product Card -->
  <ul class="product-container">

<!-- djangotags -->
      {% for laptop in laptops %}
      <li class="product-card">
        <div class="image-placeholder">
          <img src="" alt="product-img">
        </div>
        
        <div class="product-title">
          <h1>{{laptop.name}}</h1>
        </div>

        <div class="product-details-container">
          <p class="product-details">
            <span>Processor:</span><span>{{laptop.processor}}</span>
          </p>
          <p class="product-details">
            <span>Operating System:</span><span>{{laptop.os}}</span>
          </p>
          <p class="product-details">
            <span>Graphics Card:</span><span>{{laptop.graphic_card}}</span>
          </p>
          <p class="product-details">
            <span>Memory:</span><span>{{laptop.memory}}</span>
          </p>
          <p class="product-details">
            <span>Storage:</span><span>{{laptop.storage}}</span>
          </p>
          <p class="product-details">
            <span>Display:</span><span>{{laptop.display}}</span>
          </p>
          <p class="product-details">
            <span>Camera:</span><span>{{laptop.camera}}</span>
          </p>
          <p class="product-details">
            <span>Battery:</span><span>{{laptop.battery}}</span>
          </p>
          <p class="product-details">
            <span>Keyboard:</span><span>{{laptop.keyboard}}</span>
          </p>
          <p class="product-details">
            <span>Connection:</span><span>{{laptop.wifi}}</span>
          </p>
          <p class="product-details">
            <span>Warranty:</span><span>{{laptop.warranty}}</span>
          </p>
          <p class="product-details">
            <span>Color:</span><span>{{laptop.color}}</span>
          </p>
          
        </div>

        <div class="product-price">
          <h1>${{laptop.price}}</h1>
        </div>

        <div class="product-btn">
          <button>button 1</button>
        </div>
      </li>
      {% endfor %}
<!-- ==================================== -->

</ul>
    
          
  <!-- Add more product cards as required for your layout -->
</section>

<!-- Footer -->


</body>
</html>
</section>

{% endblock %}

E-COMMERCE/PRODUCT/templates/PRODUCT/pre_build_pc.html

{% extends 'master.html' %}

{% block title %}Pre-Build Pc{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/styles/pre_build_pc.css' %}">

<div class="nav-title">
    <h1>Pre-Build PC</h1>
    <p>
        <!-- to HOME                             current page -->
        <a href="#">Home</a> > <a href="#">Prebuild PC</a>    
    </p>
</div>

<section class="content">
    <!-- Filter Bar -->
<div class="prebuild-filter-bar">
    <h5>PRODUCTS</h5>
    <select>
    <option>Text here</option>
    <!-- Add more options if needed -->
    </select>
    <select>
        <option>Text here</option>
        <!-- Add more options if needed -->
    </select>
    <input type="text" placeholder="Search here...                                           🔍">
</div>

<!-- Product Grid -->
<section class="prebuild-product-grid">
    <!-- Product Card -->
    <ul class="prebuild-product-container">


        {% for pc in prebuilds %}
        <li class="prebuild-product-card">
        <div class="prebuild-image-placeholder">
            <img src="" alt="product-img">
        </div>
        
        <div class="prebuild-product-title">
            <h1>{{pc.name}}</h1>
        </div>

        <div class="prebuild-product-details-container">
            <p class="prebuild-product-details"><span>Motherboard:</span><span>{{pc.processor_unit}}</span></p>
            <p class="prebuild-product-details"><span>Processor:</span><span>{{pc.processor_unit}}</span></p>
            <p class="prebuild-product-details"><span>Storage:</span><span></span>{{pc.storage_unit}}</p>
            <p class="prebuild-product-details"><span>Memory:</span><span>{{pc.memory_unit}}</span></p>
            <p class="prebuild-product-details"><span>Power Supply:</span><span>{{pc.PSU_unit}}</span></p>
            <p class="prebuild-product-details"><span>CPU Cooler:</span><span>{{pc.CPU_cooler_unit}}</span></p>
            <p class="prebuild-product-details"><span>Graphics Card:</span><span>{{pc.GPU_unit}}</span></p>
            <p class="prebuild-product-details"><span>Case:</span><span>{{pc.case_unit}}</span></p>
            

            
        </div>

        <div class="prebuild-product-price">
            <h1>${{pc.price}}</h1>
        </div>

        <div class="prebuild-product-btn">
            <button>
                <a href="{% url 'USER:ADD_TO_CART' product_type='DESKTOP' userID=request.user.id product_id=pc.unit_id %}">Add to Cart</a>
            </button>
        </div>
        </li>
        {% endfor %}
</ul>
    
            
    <!-- Add more product cards as required for your layout -->
</section>

<!-- Footer -->


</body>
</html>

</section>
{% endblock %}

E-COMMERCE/PRODUCT/templates/PRODUCT/system_builder.html
{% extends 'master.html' %}

{% block title %}System Builder{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/styles/systembuilder.css' %}">

<div class="nav-title">
    <h1>SYSTEM BUILDER</h1>
    <p>
        <!-- to HOME                             current page -->
        <a href="#">Home</a> > <a href="#">System Builder</a>
    </p>
    
</div>
<section class="system-builder-container">
    <section class="components-section-container">
        <h1 class="components-title">Logo</h1>
        <div class="components-list-container">
            <p class="component-list-tile">Components</p>
            <ul class="list-ng-components">
                
                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #1</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #2</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #3</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #4</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #5</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #6</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #7</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #8</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #9</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #10</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>

                <li class="component">
                    <div class="component-img-name">
                        <img src="" alt="component img" class="component-img">
                        <p>Components #11</p>
                    </div>
                    
                    <button class="component-add-btn">ADD</button>
                </li>
            </ul>
        </div>
    </section>
    <section class="parts-section-container">
        <div class="parts-title-search">
            <h1>product</h1>
            <input type="text" class="parts-searchbox">
        </div>
        <div class="parts-list-container">
            <ul class="list-card-wrap">
<!-- django tags -->
                <li class="parts-card">
                    <div class="parts-product-img">
                        <img src="" alt="image here">
                        <div class="parts-product-info">
                            <h1>title</h1>
                            <p>description</p>
                        </div>
                    </div>
                    <div class="parts-price">
                        <h1>price</h1>
                    </div>
                    
                    <div class="parts-info-select">
                        <a href="">info</a>
                        <a href="">select</a>
                    </div>
                </li>

    <!-- dummy parts -->
                <li class="parts-card">
                    <div class="parts-product-img">
                        <img src="" alt="image here">
                        <div class="parts-product-info">
                            <h1>title</h1>
                            <p>description</p>
                        </div>
                    </div>
                    <div class="parts-price">
                        <h1>price</h1>
                    </div>
                    
                    <div class="parts-info-select">
                        <a href="">info</a>
                        <a href="">select</a>
                    </div>
                </li>
                <li class="parts-card">
                    <div class="parts-product-img">
                        <img src="" alt="image here">
                        <div class="parts-product-info">
                            <h1>title</h1>
                            <p>description</p>
                        </div>
                    </div>
                    <div class="parts-price">
                        <h1>price</h1>
                    </div>
                    
                    <div class="parts-info-select">
                        <a href="">info</a>
                        <a href="">select</a>
                    </div>
                </li>
                <li class="parts-card">
                    <div class="parts-product-img">
                        <img src="" alt="image here">
                        <div class="parts-product-info">
                            <h1>title</h1>
                            <p>description</p>
                        </div>
                    </div>
                    <div class="parts-price">
                        <h1>price</h1>
                    </div>
                    
                    <div class="parts-info-select">
                        <a href="">info</a>
                        <a href="">select</a>
                    </div>
                </li>
                <li class="parts-card">
                    <div class="parts-product-img">
                        <img src="" alt="image here">
                        <div class="parts-product-info">
                            <h1>title</h1>
                            <p>description</p>
                        </div>
                    </div>
                    <div class="parts-price">
                        <h1>price</h1>
                    </div>
                    
                    <div class="parts-info-select">
                        <a href="">info</a>
                        <a href="">select</a>
                    </div>
                </li>
                
            </ul>
        </div>
    </section>

    
</section>
<div class="checkout-container">
    <div class="checkout-total">
        <p>subtotal</p>
        <p>|</p>
        <p>total</p>
    </div>
    <div class="checkout-btns">
        <button class="checkout-addtocart">Add to cart</button>
        <button class="checkout-checkout" onclick="window.location.href='check_out'">Check Out</button>
    </div>
</div>
{% endblock %}